"use client";

import { Amplify } from "aws-amplify";
import { useEffect } from "react";

/**
 * Configure Amplify client-side for Next.js App Router
 * Amplify.configure is idempotent, so it's safe to call multiple times
 * 
 * According to AWS Amplify Gen2 documentation:
 * - For Next.js App Router, configure Amplify in a client component
 * - Import amplify_outputs.json dynamically to avoid build errors when file doesn't exist
 * - The outputs file is generated during Amplify deployment
 */
export const ConfigureAmplify = () => {
  useEffect(() => {
    // Dynamically import amplify_outputs.json to handle cases where it may not exist
    // This file is generated by Amplify Gen2 during deployment
    import("@/amplify_outputs.json")
      .then((outputs) => {
        // Configure Amplify with outputs from Gen2 backend
        // SSR is automatically handled for App Router when configured in a client component
        Amplify.configure(outputs.default || outputs, {
          ssr: true, // Enable SSR support for Next.js App Router
        });
      })
      .catch((error) => {
        // In local development without deployment, amplify_outputs.json may not exist
        // This is expected and the app should gracefully handle it
        console.warn(
          "Amplify outputs not found. This is expected in local development without deployment.",
          error.message
        );
      });
  }, []);

  return null;
};
